---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

'United States'

In [12]:
def answer_one():
    return df['Gold'].argmax()

answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [11]:
def answer_two():
    return (df['Gold'] - df['Gold.1']).abs().argmax()


answer_two()


'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [13]:
elegible = df[(df['Gold']>=1) & (df['Gold.1']>=1)]
elegible

# Summer  Gold  Silver  Bronze  Total  # Winter  \
Australia                     25   139     152     177    468        18   
Austria                       26    18      33      35     86        22   
Belarus                        5    12      24      39     75         6   
Belgium                       25    37      52      53    142        20   
Bulgaria                      19    51      85      78    214        19   
Canada                        25    59      99     121    279        22   
China                          9   201     146     126    473        10   
Croatia                        6     6       7      10     23         7   
Czech Republic                 5    14      15      15     44         6   
Czechoslovakia                16    49      49      45    143        16   
Estonia                       11     9       9      15     33         9   
Finland                       24   101      84     117    302        22   
France                        27   202     223     246    671        22   
Germany                       15   174     182     217    573        11   
United Team of Germany         3    28      54      36    118         3   
East Germany                   5   153     129     127    409         6   
West Germany                   5    56      67      81    204         6   
Great Britain                 27   236     272     272    780        22   
Italy                         26   198     166     185    549        22   
Japan                         21   130     126     142    398        20   
Kazakhstan                     5    16      17      19     52         6   
South Korea                   16    81      82      80    243        17   
Netherlands                   25    77      85     104    266        20   
Norway                        24    56      49      43    148        22   
Poland                        20    64      82     125    271        22   
Russia                         5   132     121     142    395         6   
Soviet Union                   9   395     319     296   1010         9   
Unified Team                   1    45      38      29    112         1   
Slovakia                       5     7       9       8     24         6   
Slovenia                       6     4       6       9     19         7   
Spain                         22    37      59      35    131        19   
Sweden                        26   143     164     176    483        22   
Switzerland                   27    47      73      65    185        22   
Ukraine                        5    33      27      55    115         6   
United States                 26   976     757     666   2399        22   
Uzbekistan                     5     5       5      10     20         6   

                        Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Australia                    5         3         4       12       43     144   
Austria                     59        78        81      218       48      77   
Belarus                      6         4         5       15       11      18   
Belgium                      1         1         3        5       45      38   
Bulgaria                     1         2         3        6       38      52   
Canada                      62        56        52      170       47     121   
China                       12        22        19       53       19     213   
Croatia                      4         6         1       11       13      10   
Czech Republic               7         9         8       24       11      21   
Czechoslovakia               2         8        15       25       32      51   
Estonia                      4         2         1        7       20      13   
Finland                     42        62        57      161       46     143   
France                      31        31        47      109       49     233   
Germany                     78        78        53      209       26     252   
United Team of Germany       8         6        

In [15]:
def answer_three():
    elegible = df[(df['Gold']>=1) & (df['Gold.1']>=1)]
    ratios = (elegible['Gold'] - elegible['Gold.1']).abs()/elegible['Gold.2']
    return ratios.argmax()

answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [23]:
import numpy as np



Afghanistan                            2.0
Algeria                               27.0
Argentina                            130.0
Armenia                               16.0
Australasia                           22.0
Australia                            923.0
Austria                              569.0
Azerbaijan                            43.0
Bahamas                               24.0
Bahrain                                1.0
Barbados                               1.0
Belarus                              154.0
Belgium                              276.0
Bermuda                                1.0
Bohemia                                5.0
Botswana                               2.0
Brazil                               184.0
British West Indies                    2.0
Bulgaria                             411.0
Burundi                                3.0
Cameroon                              12.0
Canada                               846.0
Chile                                 24.0
China      

In [24]:
def answer_four():
    points = np.zeros(len(df))
    points += df['Gold.2'] * 3
    points += df['Silver.2'] * 2
    points += df['Bronze.2']
    
    return pd.Series(points, index=df.index)

answer_four()

Afghanistan                            2.0
Algeria                               27.0
Argentina                            130.0
Armenia                               16.0
Australasia                           22.0
Australia                            923.0
Austria                              569.0
Azerbaijan                            43.0
Bahamas                               24.0
Bahrain                                1.0
Barbados                               1.0
Belarus                              154.0
Belgium                              276.0
Bermuda                                1.0
Bohemia                                5.0
Botswana                               2.0
Brazil                               184.0
British West Indies                    2.0
Bulgaria                             411.0
Burundi                                3.0
Cameroon                              12.0
Canada                               846.0
Chile                                 24.0
China      

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [25]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [34]:
census_df.groupby('STNAME').count()

SUMLEV  REGION  DIVISION  STATE  COUNTY  CTYNAME  \
STNAME                                                                   
Alabama                   68      68        68     68      68       68   
Alaska                    30      30        30     30      30       30   
Arizona                   16      16        16     16      16       16   
Arkansas                  76      76        76     76      76       76   
California                59      59        59     59      59       59   
Colorado                  65      65        65     65      65       65   
Connecticut                9       9         9      9       9        9   
Delaware                   4       4         4      4       4        4   
District of Columbia       2       2         2      2       2        2   
Florida                   68      68        68     68      68       68   
Georgia                  160     160       160    160     160      160   
Hawaii                     6       6         6      6       6        6   
Idaho                     45      45        45     45      45       45   
Illinois                 103     103       103    103     103      103   
Indiana                   93      93        93     93      93       93   
Iowa                     100     100       100    100     100      100   
Kansas                   106     106       106    106     106      106   
Kentucky                 121     121       121    121     121      121   
Louisiana                 65      65        65     65      65       65   
Maine                     17      17        17     17      17       17   
Maryland                  25      25        25     25      25       25   
Massachusetts             15      15        15     15      15       15   
Michigan                  84      84        84     84      84       84   
Minnesota                 88      88        88     88      88       88   
Mississippi               83      83        83     83      83       83   
Missouri                 116     116       116    116     116      116   
Montana                   57      57        57     57      57       57   
Nebraska                  94      94        94     94      94       94   
Nevada                    18      18        18     18      18       18   
New Hampshire             11      11        11     11      11       11   
New Jersey                22      22        22     22      22       22   
New Mexico                34      34        34     34      34       34   
New York                  63      63        63     63      63       63   
North Carolina           101     101       101    101     101      101   
North Dakota              54      54        54     54      54       54   
Ohio                      89      89        89     89      89       89   
Oklahoma                  78      78        78     78      78       78   
Oregon                    37      37        37     37      37       37   
Pennsylvania              68      68        68     68      68       68   
Rhode Island               6       6         6      6       6        6   
South Carolina            47      47        47     47      47       47   
South Dakota              67      67        67     67      67       67   
Tennessee                 96      96        96     96      96       96   
Texas                    255     255       255    255     255      255   
Utah                      30      30        30     30      30       30   
Vermont                   15      15        15     15      15       15   
Virginia                 134     134       134    134     134      134   
Washington                40      40        40     40      40       40   
West Virginia             56      56        56     56      56       56   
Wisconsin                 73      73        73     73      73       73   
Wyoming                   24      24        24     24      24       24   

                      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME                  

In [31]:
def answer_five():
    return census_df.groupby('STNAME').count().COUNTY.argmax()

answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [51]:
top_threes = census_df.groupby('STNAME')['CENSUS2010POP'].nlargest(3)
top_threes
   

STNAME                    
Alabama               0        4779736
                      37        658466
                      49        412992
Alaska                68        710231
                      71        291826
                      76         97581
Arizona               98       6392017
                      106      3817117
                      109       980263
Arkansas              114      2915918
                      174       382748
                      118       221339
California            190     37253956
                      209      9818605
                      227      3095313
Colorado              249      5029196
                      271       622263
                      266       600158
Connecticut           314      3574097
                      315       916829
                      316       894014
Delaware              323       897934
                      325       538479
                      326       197145
District of Columbia  327       60172

In [52]:
states = top_threes.groupby(level=0).sum()
states
#list(states.nlargest(3).index)

STNAME
Alabama                  5851194
Alaska                   1099638
Arizona                 11189397
Arkansas                 3520005
California              50167874
Colorado                 6251617
Connecticut              5384940
Delaware                 1633558
District of Columbia     1203446
Florida                 23045811
Georgia                 11413555
Hawaii                   2498587
Idaho                    2148870
Illinois                18942231
Indiana                  7883200
Iowa                     3688221
Kansas                   3895662
Kentucky                 5376266
Louisiana                5406095
Maine                    1807166
Maryland                 7608749
Massachusetts            8849266
Michigan                12906586
Minnesota                6964990
Mississippi              3399687
Missouri                 7662039
Montana                  1246686
Nebraska                 2628858
Nevada                   5073227
New Hampshire            2012414
New

In [53]:
list(states.nlargest(3).index)

['California', 'Texas', 'New York']

In [54]:
class CensusVariables:
    state_name = "STNAME"
    county_name = "CTYNAME"
    census_population = "CENSUS2010POP"
    region = "REGION"
    population_2014 = "POPESTIMATE2014"
    population_2015 = "POPESTIMATE2015"
    population_estimates = ["POPESTIMATE2010","POPESTIMATE2011","POPESTIMATE2012","POPESTIMATE2013",population_2014,population_2015]
    county_level = 50
    summary_level = "SUMLEV"

In [56]:
counties = census_df[census_df[
    CensusVariables.summary_level]==CensusVariables.county_level]
# this throws off the numeric index for the argmax method so reset it
counties = counties.reset_index()

# but the last question wants the original index
counties_original_index = census_df[census_df[
    CensusVariables.summary_level]==CensusVariables.county_level]

In [57]:
def answer_six():
    top_threes = counties.groupby(CensusVariables.state_name)[CensusVariables.census_population].nlargest(3)
    states = top_threes.groupby(level=0).sum()
    return list(states.nlargest(3).index)

answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [43]:

census_df[census_df.columns[9:15]] 

POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
0             4785161          4801108          4816089          4830533   
1               54660            55253            55175            55038   
2              183193           186659           190396           195126   
3               27341            27226            27159            26973   
4               22861            22733            22642            22512   
5               57373            57711            57776            57734   
6               10887            10629            10606            10628   
7               20944            20673            20408            20261   
8              118437           117768           117286           116575   
9               34098            33993            34075            34153   
10              25976            26080            26023            26084   
11              43665            43739            43697            43795   
12              13841            13593            13543            13378   
13              25767            25570            25144            25116   
14              13880            13670            13456            13467   
15              14973            14971            14921            15028   
16              50177            50448            51173            50755   
17              54514            54443            54472            54471   
18              13208            13121            12996            12875   
19              11758            11348            11195            11059   
20              37796            38060            37818            37830   
21              13853            13896            13951            13932   
22              80473            80469            80374            80756   
23              50358            50109            50324            49833   
24              43803            43178            42777            42021   
25              71142            71387            70942            70869   
26              79465            80012            80432            80883   
27              38309            38213            38034            37857   
28             104442           104236           104235           103852   
29              17231            17062            16960            16857   
...               ...              ...              ...              ...   
3163           131967           132225           132649           132758   
3164           390076           390808           392710           394025   
3165            52422            52342            52035            52213   
3166            24506            24581            24484            24332   
3167           167059           167630           168717           169486   
3168            74807            74647            74384            73996   
3169           564516           567768           577080           583131   
3170            36428            36908            37396            37647   
3171            11672            11745            11785            12002   
3172            46244            46600            47881            48121   
3173            15837            15817            15678            15787   
3174            13826            13728            14025            14343   
3175             7114             7129             7148             7160   
3176            40222            40591            41129            41024   
3177            13408            13597            13666            13565   
3178             4813             4818             4846             4846   
3179             8581             8636             8610             8619   
3180            92271            92663            94894            96006   
3181            18091            18022            17943            18328   
3182            75472            76420            78699            81156   
3183             2492             2485             247

In [44]:
census_df[census_df.columns[9:15]].max(axis=1) 

0       4858979
1         55347
2        203709
3         27341
4         22861
5         57776
6         10887
7         20944
8        118437
9         34153
10        26084
11        43943
12        13841
13        25767
14        13880
15        15072
16        51211
17        54514
18        13208
19        11758
20        38060
21        13963
22        82005
23        50358
24        43803
25        71387
26        81468
27        38309
28       104442
29        17231
         ...   
3163     133674
3164     396488
3165      52422
3166      24581
3167     169639
3168      74807
3169     586107
3170      37956
3171      12022
3172      49220
3173      15856
3174      14343
3175       7444
3176      41129
3177      13666
3178       4846
3179       8636
3180      97121
3181      18722
3182      82178
3183       2548
3184      29237
3185       8812
3186      30020
3187      10418
3188      45162
3189      23125
3190      21102
3191       8545
3192       7234
dtype: int64

In [58]:
def answer_seven():
     return counties.iloc[(counties[CensusVariables.population_estimates].max(axis=1) - counties[CensusVariables.population_estimates].min(axis=1)
     ).argmax()][CensusVariables.county_name]

answer_seven()    

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [47]:
census_df.head()


SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [48]:
regions = census_df[(census_df['REGION']==1) |(census_df['REGION']==2)]
washingtons = regions[regions['CTYNAME'].str.startswith("Washington")]
washingtons

SUMLEV  REGION  DIVISION  STATE  COUNTY        STNAME  \
703       50       2         3     17     189      Illinois   
799       50       2         3     18     175       Indiana   
896       50       2         4     19     183          Iowa   
1005      50       2         4     20     201        Kansas   
1211      50       1         1     23      29         Maine   
1419      50       2         4     27     163     Minnesota   
1618      50       2         4     29     221      Missouri   
1770      50       2         4     31     177      Nebraska   
1918      50       1         2     36     115      New York   
2162      50       2         3     39     167          Ohio   
2345      50       1         2     42     125  Pennsylvania   
2355      50       1         1     44       9  Rhode Island   
2863      50       1         1     50      23       Vermont   
3163      50       2         3     55     131     Wisconsin   

                CTYNAME  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
703   Washington County          14716              14716            14701   
799   Washington County          28262              28262            28284   
896   Washington County          21704              21704            21697   
1005  Washington County           5799               5799             5782   
1211  Washington County          32856              32856            32824   
1419  Washington County         238136             238134           238995   
1618  Washington County          25195              25196            25177   
1770  Washington County          20234              20234            20275   
1918  Washington County          63216              63216            63292   
2162  Washington County          61778              61778            61708   
2345  Washington County         207820             207820           207877   
2355  Washington County         126979             127094           127085   
2863  Washington County          59534              59526            59570   
3163  Washington County         131887             131885           131967   

         ...       RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
703      ...              -8.057633          2.192006        -12.192182   
799      ...              -3.683894         -9.517699         -5.310179   
896      ...               5.743693          2.468684         -0.364282   
1005     ...              10.504563        -18.164519        -18.821460   
1211     ...               0.213626         -3.280699         -4.262285   
1419     ...               2.555118          3.260957          2.285952   
1618     ...              -5.130755         -2.389867          0.079577   
1770     ...              -1.874784         -1.331459         -4.492607   
1918     ...              -3.719090         -1.776030         -4.165839   
2162     ...               0.129798          0.780050         -0.455611   
2345     ...               3.683135          3.260434          1.219337   
2355     ...              -4.669304         -2.659574          1.551904   
2863     ...              -1.578161         -5.617505         -3.407759   
3163     ...              -0.794876          0.785279         -2.215465   

      RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
703          -2.775850        -10.605638    -8.125918     2.123506   
799           0.717901         -5.454774    -3.258829    -9.161231   
896           0.272171          1.849596     5.881542     2.560117   
1005         -5.501819         -6.948156    12.054417   -16.780555   
1211         -9.111049         -4.284274     0.366217    -2.790127   
1419          3.072543          0.678755     4.178076     4.907905   
1618         -1.592420        -11.511311    -5.011435    -2.389867   
1770         -0.889284         -3.998716    -1.825448    -1.282146   
1918         -4.954213         -2.342897    -3.418398    -1.522311   
2162         -2.137467          0.016355     0.227147     1.023

In [49]:
grew = washingtons[washingtons['POPESTIMATE2015'] > washingtons['POPESTIMATE2014']]
grew[['STNAME','CTYNAME']]

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [50]:
def answer_eight():
    regions = census_df[(census_df['REGION']==1) |(census_df['REGION']==2)]
    washingtons = regions[regions['CTYNAME'].str.startswith("Washington")]
    grew = washingtons[washingtons['POPESTIMATE2015'] > washingtons['POPESTIMATE2014']]
 
    return grew[['STNAME','CTYNAME']]

answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County